""" woods """
s1 = [f"""{input('''You are following the quiet path. Upon further
investigation you come upon a fork in the path, do you go left or
right?''')}""",
"You went left...",
"it becomes darker...",
"You see a drogon!",
"You were killed by the dragon!",
"You kill the dragon!",
"You see a dragon!",
"You kill the dragon!",
"""Further along you see a treacherous bridge, as you begin
walking closer you see an old man in dark clothes.""",
"""Stop. Who would cross this bridge must answer these three questions, ere the
other side he see.""",
f"{input('What is your name?')}",
"That is not your name, you have ben cast off the bridge!",
f"{input('What is your favorite color?')}",
f"""{'''(What is the air-speed velocity of an
unladen swallow? (Hint, ask the gatekeeper an african or european swallow?))'''}""",
"The gatekeeper stammers and makes an exuse, then is cast off the bridge.",
"You travel further in the woods and come across a small village.",
"The people there seem primal and hostile."
f"{input('What do you do?[stay or travel on]')}"
f"{input('What do you want to do with the people? [talk or kill]')}",
"You talk to the strangers, they act very nice and welcoming...",
"You go into one of the tents and see a dead body...",
"The strangers capture you and everything goes black...",
"They gave a good fight, but you have succesfully killed the strangers.",
"The woods opens up, and you see the light...",

"You went right, it is dry, foggy,  and life seems sparse."),
"As you venture down the path you hear scurried movement and see",
"You start to get anxious...",
"You look up and suddenly see tall people draped in dark ragged clothing!",

"SHRUBBERY!",
"Your task is to now find a shrubbery, where do you look?",
"You enter the cave...",
"There is nothing but rocks. (Suprise)",
"nYou see writing etched in the wall, it reads",
"The monster appears and kills you. :(",
"You go to the town shrubber.",
cname  ": 'Hello I would like to purchase a shrubbery.'",
"Shrubber: 'And why do you think I would have that?'",
cname  ": 'Becuase you're the shrubber...'",
Shrubber: 'And?'",
cname  ": 'What?'",
"Shrubber: 'Ok fine I will sell you a shrubbery for...'",
"A CHICKEN!'",
"You kill the shrubber and take the shrubbery.",
"You return to the knights of Ni and give them the shrubbery.",
"They say, 'Thank you for the shrubbery...'",
cname ": Can I pass?",
"Knights of Ni: To pass we need a...",
"You kill the Knights of Ni.",
"You search around the forest.",
"You search the forest.",
"You walk along the path.",
"Ow! You tripped and fell down a large hole.",
"It was a rabbit hole.",
"This isn't very good....",]
